packages:
  - 'apps/*'
  - 'packages/dynamicons/core'
  - 'packages/dynamicons/ext'
  - 'packages/terminal-actions/core'
  - 'packages/terminal-actions/ext'
  - 'packages/utilities-core'
  - 'packages/tools'
  