packages:
  - apps/*
  - packages/shared/*
  - packages/dynamicons/core
  - packages/dynamicons/ext
  - packages/context-cherry-picker-ext

onlyBuiltDependencies:
  - bun
  - core-js
  - esbuild
  - puppeteer
  - sharp
